# Generated by Django 5.2.14 on 2026-05-11 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('admin1', models.CharField(blank=True, max_length=255, null=True)),
                ('admin2', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_station_id', models.IntegerField(blank=True, null=True)),
                ('nearest_station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'latitude', 'longitude')},
            },
        ),
    ]
