# Generated by Django 5.2.14 on 2026-05-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQINorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_code', models.CharField(max_length=50)),
                ('index_level', models.CharField(max_length=100)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('color_hex', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gios_id', models.IntegerField(unique=True)),
                ('station_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city_name', models.CharField(max_length=255)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gios_id', models.IntegerField(unique=True)),
                ('param_name', models.CharField(max_length=100)),
                ('param_code', models.CharField(max_length=50)),
                ('param_formula', models.CharField(blank=True, max_length=100, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='air_quality.station')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='air_quality.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('sensor', 'timestamp')},
            },
        ),
    ]
